### ISSUE TITLE
globus_auth is breaking ermrest and hatrac travis builds

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#20]
The conditionalization of all the oauth2 dependencies is not working. The travis deploys for other services use the local db providers and do not expect oauth dependencies to be in place. This is a recent regression.

See [failed ermrest test cycle](https://s3.amazonaws.com/archive.travis-ci.org/jobs/113023832/log.txt) which ends with:

```
$ sudo -H -u ermrest ermrest-webauthn2-manage adduser test1

Traceback (most recent call last):

  File "/usr/bin/ermrest-webauthn2-manage", line 8, in <module>

    import ermrest

  File "/usr/lib/python2.7/dist-packages/ermrest/__init__.py", line 18, in <module>

    import model

  File "/usr/lib/python2.7/dist-packages/ermrest/model/__init__.py", line 28, in <module>

    from .column import Column

  File "/usr/lib/python2.7/dist-packages/ermrest/model/column.py", line 22, in <module>

    from ..util import sql_identifier, sql_literal

  File "/usr/lib/python2.7/dist-packages/ermrest/util.py", line 28, in <module>

    from webauthn2.util import urlquote, negotiated_content_type

  File "/usr/lib/python2.7/dist-packages/webauthn2/__init__.py", line 26, in <module>

    import rest

  File "/usr/lib/python2.7/dist-packages/webauthn2/rest.py", line 70, in <module>

    from manager import Manager, Context

  File "/usr/lib/python2.7/dist-packages/webauthn2/manager.py", line 89, in <module>

    import providers

  File "/usr/lib/python2.7/dist-packages/webauthn2/providers/__init__.py", line 29, in <module>

    import globus_auth

  File "/usr/lib/python2.7/dist-packages/webauthn2/providers/globus_auth.py", line 24, in <module>

    import oauth2

  File "/usr/lib/python2.7/dist-packages/webauthn2/providers/oauth2.py", line 60, in <module>

    import oauth2client.client

ImportError: No module named oauth2client.client
```

**Comment by karlcz** [comment]
@hongsudt I think this should be in the current milestone as it prevents the CI tests on ermrest and hatrac.  it's probably a pretty small fix for @ljpearlman

**Comment by ljpearlman** [comment]
Sorry about that. Just pushed a fix.
