### ISSUE TITLE
Refactor standalone /authn REST API

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#9]
Rather than embedding webauthn endpoints under `/ermrest/authn/`, deploy another WSGI service under the `/authn/` path on the server using its own daemon account and a single copy of `webauthn_config.json`.  Make ERMrest and Hatrac deployments reference this configuration to setup their basic message-level authentication but otherwise omit authn endpoints from those services.

This will make it easier to compose different subsets of services on a particular host or even do single-sign-on across a domain in the future.

**Comment by karlcz** [comment]
I think this is actually working and ready to review now.  Not sure if we should wait until we can hook up the new apache module before merging into master though...?

**Comment by ljpearlman** [comment]
@karlcz - is there a specific commit I should be testing with?

**Comment by karlcz** [comment]
head of restapi branch

**Comment by ljpearlman** [comment]
I tried that on my test machine (checked out restapi webauthn, then ran the hourly dev-update script) and got this:

[Thu May 26 15:29:23.781134 2016] [:error] [pid 2292] [remote 128.9.136.72:0] mod_wsgi (pid=2292): Target WSGI script '/usr/lib/python2.7/site-packages/ermrest/ermrest.wsgi' cannot be loaded as Python module.
[Thu May 26 15:29:23.781173 2016] [:error] [pid 2292] [remote 128.9.136.72:0] mod_wsgi (pid=2292): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/ermrest/ermrest.wsgi'.
[Thu May 26 15:29:23.781204 2016] [:error] [pid 2292] [remote 128.9.136.72:0] Traceback (most recent call last):
[Thu May 26 15:29:23.781247 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/ermrest/ermrest.wsgi", line 19, in <module>
[Thu May 26 15:29:23.781321 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     import ermrest
[Thu May 26 15:29:23.781333 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/ermrest/__init__.py", line 18, in <module>
[Thu May 26 15:29:23.781407 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     import model
[Thu May 26 15:29:23.781419 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/ermrest/model/__init__.py", line 28, in <module>
[Thu May 26 15:29:23.781467 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     from .column import Column
[Thu May 26 15:29:23.781480 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/ermrest/model/column.py", line 22, in <module>
[Thu May 26 15:29:23.781588 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     from ..util import sql_identifier, sql_literal
[Thu May 26 15:29:23.781601 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/ermrest/util.py", line 28, in <module>
[Thu May 26 15:29:23.781670 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     from webauthn2.util import urlquote, negotiated_content_type
[Thu May 26 15:29:23.781682 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/webauthn2/__init__.py", line 26, in <module>
[Thu May 26 15:29:23.781733 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     import rest
[Thu May 26 15:29:23.781744 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/webauthn2/rest.py", line 70, in <module>
[Thu May 26 15:29:23.782024 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     from manager import Manager, Context
[Thu May 26 15:29:23.782053 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/webauthn2/manager.py", line 319, in <module>
[Thu May 26 15:29:23.782157 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     nullmanager = Manager()
[Thu May 26 15:29:23.782169 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/webauthn2/manager.py", line 234, in __init__
[Thu May 26 15:29:23.782188 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     overrides = util.merge_config(jsonFileName='%s/webauthn2_config.json' % os.path.expanduser("~webauthn"))
[Thu May 26 15:29:23.782197 2016] [:error] [pid 2292] [remote 128.9.136.72:0]   File "/usr/lib/python2.7/site-packages/webauthn2/util.py", line 149, in merge_config
[Thu May 26 15:29:23.782363 2016] [:error] [pid 2292] [remote 128.9.136.72:0]     f = open(fname)
[Thu May 26 15:29:23.782394 2016] [:error] [pid 2292] [remote 128.9.136.72:0] IOError: [Errno 2] No such file or directory: '/home/ermrest/~webauthn/webauthn2_config.json'

**Comment by karlcz** [comment]
You need to do a webauthn 'make deploy' as root in the source tree.
This deploys the database sample config and the new daemon account and
database.

If you want to change the webauthn config, you need to replace the
~webauthn/webauthn2_config.json with your revised one and run
webauthn2-deploy again to create the corresponding DB schema.  If you
want to do it in one go, put this config file in place *before*
running the make deploy step.

The webauthn config data in ~ermrest and/or ~hatrac daemon accounts are
no longer relevant on this branch.

**Comment by ljpearlman** [comment]
I think we need a convenient way to upgrade existing deployments; maybe something that does this:

1. Create the webauthn account
2. Generate ~webauthn/webauthn_config.json from the existing ~ermrest/ermrest_config.json
3. Create database roles and change ownership/permissions of the existing webauthn schema, but leave the contents of the tables alone.

**Comment by karlcz** [comment]
It's not even going to be in the same database...  the new schema
will be in the webauthn DB.

I'm not very concerned about this upgrade outside of a controlled devops
scenario.  I expect those steps to be done by the provisioning recipes
and not by any code specifically in the webauthn repo.
